"""tilt-generated

Revision ID: cfb17149867a
Revises: 0007
Create Date: 2026-08-02 08:15:33.961572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb17149867a'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_model_artifacts_deleted_at'), 'model_artifacts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_model_artifacts_id'), 'model_artifacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_artifacts_id'), table_name='model_artifacts')
    op.drop_index(op.f('ix_model_artifacts_deleted_at'), table_name='model_artifacts')
    # ### end Alembic commands ###
